load_module "modules/ngx_http_headers_more_filter_module.so";

worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {

    access_log /dev/stdout;
    error_log /dev/stdout;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    client_max_body_size 16M; # max size

    server {

        listen       80;

        resolver 127.0.0.11 ipv6=off valid=30s;

        server_tokens off;
        more_set_headers "Server: I'm a webina server proxy";

        include mime.types;
        default_type application/octet-stream;

        sendfile on;

        location  ~ (/more-info) {
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            set $moreinfo_backend "http://webina_moreinfo";

            proxy_pass $moreinfo_backend;
        }

        location /heartbeat {
            expires -1;
            add_header Pragma "no-cache";
            add_header Cache-Control "no-store, no-cache, must-revalidate, post-check=0, pre-check=0";
            return 204;
        }

        location / {
            proxy_set_header HOST $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            set $webina_backend "http://webina_main";

            # Avoid 504 http timeout errors
            proxy_connect_timeout       605;
            proxy_send_timeout          605;
            proxy_read_timeout          605;
            send_timeout                605;
            keepalive_timeout           605;
            client_body_timeout         605;


            proxy_pass $webina_backend;
        }

        error_page 404 /404.json;
        location = /404.json {
          root /usr/share/nginx/html;
          internal;
        }

    }
}

